### PR TITLE
Remap TC Draco aspect if another mod overwrote it

### LINKED ISSUE #61: Thaumcraft aspect "Draco" conflicting with Thaumic Additions "Draco"
Ice and Fire adds a new aspect called "Draco" to Thaumcraft, but Thaumic Additions also adds "Draco" which causes a conflict.
The conflict causes the Draco aspect to have a fake version which is extremely unstable. Trying to extract this fake "Draco" as essentia crystals or trying to obtain a phial of it will fail to form the desired item. Directly moving this essentia to a jar and breaking it will **sometimes** crash the game. The game cannot handle a container that is filled with this fake aspect.

This is the part of IaC that handles the thaumcraft compat.

static Aspect getOrCreateAspect(String tag, int color, Aspect[] components, ResourceLocation image, int blend) {
        Aspect a = **Aspect.getAspect(tag);**
        if (a != null) return a;
        return new Aspect(tag, color, components, image, blend);

There is a NEI addon that allows the player to see all aspects that exist in the game. Thaumic Additions "Draco" is taking precedence over the IaC version. (note the search term "draco" only finds one aspect)

As for the item aspects, Ender dragon egg contains 100 real "Draco" while IaC items have this fake "Draco". It seems that the fake "Draco" has the wrong color and ResourceLocation.
I suspect that the bolded area only fetches the name and completely forgets about the rest. That is why the fake "Draco" has the IaC-designated colors and image.

Since I am relatively new to Java development, I do not have the knowledge to properly fix this. I have no idea how to properly decompile and re-compile a mod. I am sorry I could not help further.

### PR DESCRIPTION
**Pull request by jchung01**
A bit of a workaround to account for Thaumic Additions: Reconstructed (TAR) overwriting the "Draco" aspect that I&F also adds. TAR 12.7.9 removes I&F's Draco from the aspect registry, so we need to remap I&F Draco from all registered items/entities to TAR's Draco. Specific load order is handled by TAR (TAR after I&F), and messing with it on our side would not solve the issue anyway (see comment on `ThaumcraftCompat#remapDraco`).
Fixes #61. It does mean you'll never see I&F's Draco icon in-game with TAR, but it keeps the Draco aspect consistent on all items this way.

### CODE REVIEW

File: src/main/java/com/github/alexthe666/iceandfire/compat/thaumcraft/ThaumcraftCompat.java [hunk 1]
```diff
@@ -18,228 +22,266 @@
...
+     * So we need to remap the reference and all our items to the new Draco aspect.
+     */
+    public void remapDraco() {
+        // Nothing overwrote our Draco aspect.
+        if (DRAGON.equals(Aspect.getAspect("draco"))) {
+            dracoItems.clear();
+            return;
+        }
+        IceAndFire.logger.info("Detected a mod overwrote I&F's Draco aspect: remapping " + dracoItems.size() + " entries.");
+        Aspect draco = Aspect.getAspect("draco");
```
Comment (democat3457) [inline src/main/java/com/github/alexthe666/iceandfire/compat/thaumcraft/ThaumcraftCompat.java]: Could this get renamed to something like `realDraco` to further set apart the actual draco aspect versus I&F's? Also, this can get moved to above the `DRAGON.equals` so we don't have to fetch the aspect twice.

**Review by democat3457 — APPROVED** [review]
